version: "3.7"
services:
  vote_bot:
    image: votebot:2.0
    build:
      context: .
    init: true
    restart: always
    volumes:
      - votebot-data:/voteBot/data:rw
    environment:
      - BOT_TOKEN=${BOT_TOKEN:?BOT_TOKEN is not set. Check your .env file}
      - ADMIN_ID=${ADMIN_ID:?ADMIN_ID is not set. Check your .env file}
      - MEETING_CHANNEL_ID=${MEETING_CHANNEL_ID:?MEETING_CHANNEL_ID is not set. Check your .env file}
      - PAPER_SUGGESTING_CHANNEL_ID=${PAPER_SUGGESTING_CHANNEL_ID:?PAPER_SUGGESTING_CHANNEL_ID is not set. Check your .env file}
      - PAPER_VOTING_CHANNEL_ID=${PAPER_VOTING_CHANNEL_ID:?PAPER_VOTING_CHANNEL_ID is not set. Check your .env file}

volumes:
  votebot-data:
